version: '3.4'

services:
  honeypotpi:
    image: alpha
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
     - "80:80"
     - "443:443"
     - "11829:11829"
    volumes:
     - "/home/pi/Docker/listfiles:/home/listfiles"
     - "/home/pi/Docker/savedump:/home/serverdump"
     - "/home/pi/Docker/htmlmainweb/HoneyPi-Website:/home/htmlmainweb"

#volumes:
  

#networks:
#  my_network1:
#    driver: bridge
#  host:
#    driver: host
#    ports:
#      - 80:80
#      - 443:443
#      - 11829:11829