version: '3.4'

services:
  honeypotpi:
    image: alpha
    build:
      context: .
      dockerfile: ./Dockerfile

volumes:
  

networks:
  my_network1:
    driver: bridge
    ports:
      - 63599:63599
      - 11535:11535
  host:
    driver: host
    ports:
      - 80:80
      - 443:443
      - 11829:11829
      - 11830:11830
      - 22221:2221
      - 8080:8080